# This is the config file used for first deploy of neutrino
#
# This config file deploys the entire neutrino application
# For now, docker images are deployed only to the local server
# and AWS services are deployes as well
#
# The deploy follows sequence specified in this file. So if order of deploys
# are important, please specify them in order

# Example setup
# name:
#    # relative is relative to NEUTRINO_HOME, local is relatibe to 'pwd':
#    pathtype: relative | local | absolute
#    # either relative or absolute path to init filenames
#    filedir: abc/def/...
#    filenames:
#        - init_fn1.py: arg1 arg2 . . . 
#        - init_fn2.py: arg1 arg2 . . . 

# Setup IAM
# Setup Roles and Policies (for now, roles only. Policies are manual)
aws_iam:
    valid: False
    pathtype: relative
    filedir: source/deploys/cloud/aws/aws_iam
    filenames:
        - init_iam.py: none

# Setup DynamoDB
aws_dynamodb:
    valid: True
    pathtype: relative
    filedir: source/deploys/cloud/aws/aws_dynamodb
    filenames:
        - init_dynamodb.py: none



# Setup AWS IoT

# Setup things, thing types, etc.

# Setup Lambdas

