# This is the config file used for taking down the neutrino app
#
# The takedown follows sequence specified in this file. So if order of deploys
# are important, please specify them in order

# Example
# name:
#    # relative is relative to NEUTRINO_HOME, local is relatibe to 'pwd':
#    pathtype: relative | local | absolute
#    # either relative or absolute path to init filenames
#    filedir: abc/def/...
#    filenames:
#        - init_fn1.py: arg1 arg2 . . . 
#        - init_fn2.py: arg1 arg2 . . . 

# Takedown IAM
# Takedown Roles and Policies (for now, roles only. Policies are manual)
aws_iam:
    valid: False    # tested
    pathtype: relative
    filedir: source/deploys/cloud/aws/aws_iam
    filenames:
        - down_iam.py: none

# Takedown DynamoDB
aws_dynamodb:
    valid: True # tested
    pathtype: relative
    filedir: source/deploys/cloud/aws/aws_dynamodb
    filenames:
        - down_dynamodb.py: none

# Takedown AWS IoT
#    - Sets up things, thing types, etc.
aws_iot_core:
    valid: False # tested
    pathtype: relative
    filedir: source/deploys/cloud/aws/aws_iot_core
    filenames:
        - down_iot_core.py: none

# Takedown Lambdas
aws_lambda:
    valid: False # tested
    pathtype: relative
    filedir: source/deploys/cloud/aws/aws_lambda
    filenames:
        - down_lambda.py: none
