# This file contains configs for AWS DynamoDB database
# This config lists all of the tables that needs to be created in DynamoDB
# and the parameters associated with it

# General structure of a db config
#
#    - table_name:                     # Name of the Table
#          primary_key: test1_pri      # Primary (or hash) key name
#          secondary_key: test1_sec    # Secondary (or sort) key name
#          table_schema:               # Schema of the table. This should be
#                                      # a list of AttributeName:AttributeType
#                                      # pairs. At minimul schema of pri and sec
#                                      # keys should be specified
#              - AttributeName: AttributeType   # List of attr name and type
#              - AttributeName: AttributeType   # AttributeType can be:
#                                               # S for string
#                                               # N for Number
#                                               # B for boolean
#          billing_mode: PAY_PER_REQUEST or PROVISIONED
#          billing_mode_params:        # If billing mode is PROVISIONED
#           read_capacity_units: 123   # Then read_capacity_units and
#           write_capacity_units: 123  # write_capacity_units are needed
#              



create_dynamodb_tables:
    - test_db1:
          primary_key: test1_pri 
          secondary_key: test1_sec
          table_schema:
               - test1_pri: S
               - test1_sec: N
          billing_mode: PAY_PER_REQUEST
          billing_mode_params:
              read_capacity_units: 20
              write_capacity_units: 20

