# Config file for initializing AWS IAM
# init_path 

create_roles:
    - role_name: neutrino_alpha1
      trust_policy: aws_policy_allow_lambda
      path: '/' 
      description: "neutrino policy to allow: lambda access"
      tags:
          # tags are of form: Key: Value
        - project: Neutrino
        - project_ver: alpha_v1
        - access: all_lambda



# Trust policies are defined below. The "create_roles" config above
# use the trust policies defined below, linked by policy_name
trust_policies:
    aws_policy_allow_lambda:
        Version:  "2012-10-17"
        Statement:
            - Effect: Allow
              Principal:
                  Service: lambda.amazonaws.com
              Action: "sts:AssumeRole"
