# This file contains configs for AWS DynamoDB database
# This config lists all of the tables that needs to be created in DynamoDB
# and the parameters associated with it

# General structure of a db config
#
#    - table_name:                     # Name of the Table
#          primary_key: detect_time100 # Primary (or hash) key name
#          secondary_key: obj_index    # Secondary (or sort) key name
#          table_schema:               # Schema of the table. This should be
#                                      # a list of AttributeName:AttributeType
#                                      # pairs. At minimul schema of pri and sec
#                                      # keys should be specified
#              - AttributeName: AttributeType   # List of attr name and type
#              - AttributeName: AttributeType   # AttributeType can be:
#                                               # S for string
#                                               # N for Number
#                                               # B for boolean
#          billing_mode: PAY_PER_REQUEST or PROVISIONED
#          billing_mode_params:        # If billing mode is PROVISIONED
#           read_capacity_units: 123   # Then read_capacity_units and
#           write_capacity_units: 123  # write_capacity_units are needed
#              



create_dynamodb_tables:
    - na1_cam_v1p1:    # Full expansion: 
                       #      na1: neutrino alpha v1
                       #      cam_v1p1:  Camera stream table. Version 1.1
          primary_key: detect_time100
          secondary_key: obj_index
          table_schema:               # This is table schema version: SV2
               - detect_time100: N    # Primary key
               - obj_index: N         # Secondary key
               - detect_time_hr: S
               - confidence: S
               - found: S
               - stream_group_name: S
               - stream_name: S
               - msg_format_version: S
               - startX: N
               - endX: N
               - startY: N
               - endY: N
          billing_mode: PAY_PER_REQUEST
          billing_mode_params:
              read_capacity_units: 20
              write_capacity_units: 20
