# ''' Contains configs for all AWS IoT Core related init and run '''
aws_iot_core_init:
    thing_types:
        - cam_type:
              properties:
                  thingTypeDescription: "Camera Type for project Neutrino"
                  searchableAttributes: 
                      - camera
                      - cam
              tags:
                  - "Key: type, Value: camera"
    # In theory, things should be the same as valid camera names or 
    # sensor names. But in the spirit of moving faster, doing this weird thing
    things:
        aruba_slr01_bldg_d_f1_elevators:
            thing_type_name: cam_type
        aruba_slr01_bldg_d_f1_elevators:
            thing_type_name: cam_type
        aruba_slr01_bldg_d_f1_rear_lobby_entrance:
            thing_type_name: cam_type
        aruba_slr01_bldg_d_f2_elevators:
            thing_type_name: cam_type
        aruba_slr01_bldg_d_f3_elevators:
            thing_type_name: cam_type
        aruba_slr01_bldg_d_f4_elevators:
            thing_type_name: cam_type
        aruba_slr01_bldg_d_f5_elevators:
            thing_type_name: cam_type
        aruba_slr01_bldg_d_f1_s_lobby_rnd:
            thing_type_name: cam_type
        aruba_slr01_bldg_d_f4_helpdesk:
            thing_type_name: cam_type
        aruba_slr01_bldg_d_f2_archimedes:
            thing_type_name: cam_type

