# This config will run a set of containers that connect to 
# various cameras and publish the resulting images to a pub/sub. 
# Other containers can then subscribe to it.

version: "3.7"
services:

  cam2pub_1:
    image: local/cam2pub:0.1
    container_name: cam2pub_slr01_bldg_d_f1_elevators
    environment:
        - NEUTRINO_VALID_CAMS=Aruba_SLR01_Cams:slr01_bldg_d_f1_elevators
        - LOG_TO_FILE=/var/log/Aruba_SLR01_Cams_slr01_bldg_d_f1_elevators.log
    networks:
      - network_cam2pub_1
    volumes:
        - /opt/videos:/opt/videos/
        # This is to provide the creds. May not be the best way to do this
        - ~/.aws/:/root/.aws/
    deploy:
      restart_policy:
        condition: on-failure

  cam2pub_2:
    image: local/cam2pub:0.1
    container_name: slr01_bldg_d_f1_rear_lobby_entrance
    environment:
        - NEUTRINO_VALID_CAMS=Aruba_SLR01_Cams:slr01_bldg_d_f1_rear_lobby_entrance
        - LOG_TO_FILE=/var/log/Aruba_SLR01_Cams_slr01_bldg_d_f1_rear_lobby_entrance.log
    networks:
      - network_cam2pub_2
    volumes:
        - /opt/videos:/opt/videos/
        # This is to provide the creds. May not be the best way to do this
        - ~/.aws/:/root/.aws/
    deploy:
      restart_policy:
        condition: on-failure

networks:
  network_cam2pub_1:
  network_cam2pub_2:

