# This config will run a set of containers that connect to 
# various cameras and publish the resulting images to a pub/sub. 
# Other containers can then subscribe to it.

version: "3.7"
services:

  cam2pub_1:
    image: local/cam2pub:0.1
    container_name: cam2pub_1
    environment:
        - NEUTRINO_VALID_CAMS=slr01_bldg_d_f1_elevators
    networks:
      - network_cam2pub_1
    volumes:
        - /opt/videos:/opt/videos/
    deploy:
      restart_policy:
        condition: on-failure

networks:
  network_cam2pub_1:

